import type { Categoria, Producto } from "./tipos";

/** En el orden en que se recorre un REWE: fresco primero, químicos al final. */
export const CATEGORIAS: Categoria[] = [
  { id: "frutas", nombre: "Frutas y verduras", nombreDe: "Obst & Gemüse", emoji: "🥬" },
  { id: "carnes", nombre: "Carnes y pescados", nombreDe: "Fleisch & Fisch", emoji: "🥩" },
  { id: "lacteos", nombre: "Lácteos y huevos", nombreDe: "Milch & Eier", emoji: "🥛" },
  { id: "panaderia", nombre: "Panadería", nombreDe: "Backwaren", emoji: "🥖" },
  { id: "despensa", nombre: "Despensa", nombreDe: "Vorrat", emoji: "🥫" },
  { id: "congelados", nombre: "Congelados", nombreDe: "Tiefkühl", emoji: "🧊" },
  { id: "bebidas", nombre: "Bebidas", nombreDe: "Getränke", emoji: "🥤" },
  { id: "snacks", nombre: "Snacks", nombreDe: "Snacks & Süßes", emoji: "🍪" },
  { id: "limpieza", nombre: "Limpieza", nombreDe: "Haushalt", emoji: "🧽" },
  { id: "cuidado", nombre: "Cuidado personal", nombreDe: "Drogerie", emoji: "🧴" },
  { id: "mascotas", nombre: "Mascotas", nombreDe: "Tierbedarf", emoji: "🐕" },
  { id: "otros", nombre: "Otros", nombreDe: "Sonstiges", emoji: "📦" },
];

export const CATEGORIA_POR_ID = Object.fromEntries(
  CATEGORIAS.map((c) => [c.id, c]),
) as Record<Categoria["id"], Categoria>;

const p = (
  nombre: string,
  nombreDe: string,
  emoji: string,
  categoria: Producto["categoria"],
): Producto => ({ nombre, nombreDe, emoji, categoria });

/**
 * Lo que de verdad se consigue en Berlín: REWE, Edeka, Aldi, Lidl y dm, más lo
 * latino que se encuentra en el turco o en el asiático (plátano, yuca, cilantro).
 * El nombre alemán va al lado para poder pedirlo o buscarlo en el pasillo.
 */
export const CATALOGO: Producto[] = [
  // Frutas y verduras
  p("Aguacate", "Avocado", "🥑", "frutas"),
  p("Banano", "Banane", "🍌", "frutas"),
  p("Manzana", "Apfel", "🍎", "frutas"),
  p("Pera", "Birne", "🍐", "frutas"),
  p("Naranja", "Orange", "🍊", "frutas"),
  p("Mandarina", "Mandarine", "🍊", "frutas"),
  p("Limón", "Zitrone", "🍋", "frutas"),
  p("Fresas", "Erdbeeren", "🍓", "frutas"),
  p("Arándanos", "Heidelbeeren", "🫐", "frutas"),
  p("Uvas", "Trauben", "🍇", "frutas"),
  p("Mango", "Mango", "🥭", "frutas"),
  p("Piña", "Ananas", "🍍", "frutas"),
  p("Sandía", "Wassermelone", "🍉", "frutas"),
  p("Melón", "Melone", "🍈", "frutas"),
  p("Kiwi", "Kiwi", "🥝", "frutas"),
  p("Durazno", "Pfirsich", "🍑", "frutas"),
  p("Tomate", "Tomaten", "🍅", "frutas"),
  p("Tomate cherry", "Cherrytomaten", "🍅", "frutas"),
  p("Cebolla", "Zwiebeln", "🧅", "frutas"),
  p("Cebolla roja", "Rote Zwiebeln", "🧅", "frutas"),
  p("Cebolla larga", "Frühlingszwiebeln", "🌿", "frutas"),
  p("Ajo", "Knoblauch", "🧄", "frutas"),
  p("Papa", "Kartoffeln", "🥔", "frutas"),
  p("Batata", "Süßkartoffel", "🍠", "frutas"),
  p("Zanahoria", "Karotten", "🥕", "frutas"),
  p("Pimentón", "Paprika", "🫑", "frutas"),
  p("Pepino", "Gurke", "🥒", "frutas"),
  p("Calabacín", "Zucchini", "🥒", "frutas"),
  p("Berenjena", "Aubergine", "🍆", "frutas"),
  p("Champiñones", "Champignons", "🍄", "frutas"),
  p("Brócoli", "Brokkoli", "🥦", "frutas"),
  p("Coliflor", "Blumenkohl", "🥦", "frutas"),
  p("Espinaca", "Spinat", "🥬", "frutas"),
  p("Lechuga", "Kopfsalat", "🥬", "frutas"),
  p("Rúcula", "Rucola", "🥬", "frutas"),
  p("Repollo", "Weißkohl", "🥬", "frutas"),
  p("Puerro", "Lauch", "🥬", "frutas"),
  p("Apio", "Sellerie", "🥬", "frutas"),
  p("Espárragos", "Spargel", "🌿", "frutas"),
  p("Habichuelas", "Grüne Bohnen", "🫛", "frutas"),
  p("Maíz", "Mais", "🌽", "frutas"),
  p("Jengibre", "Ingwer", "🫚", "frutas"),
  p("Cilantro", "Koriander", "🌿", "frutas"),
  p("Perejil", "Petersilie", "🌿", "frutas"),
  p("Albahaca", "Basilikum", "🌿", "frutas"),
  p("Ají picante", "Chili", "🌶️", "frutas"),
  p("Plátano verde", "Kochbanane", "🍌", "frutas"),
  p("Yuca", "Maniok", "🥔", "frutas"),

  // Carnes y pescados
  p("Pechuga de pollo", "Hähnchenbrust", "🍗", "carnes"),
  p("Muslos de pollo", "Hähnchenschenkel", "🍗", "carnes"),
  p("Pollo entero", "Hähnchen", "🍗", "carnes"),
  p("Carne molida", "Hackfleisch", "🥩", "carnes"),
  p("Carne de res", "Rindfleisch", "🥩", "carnes"),
  p("Bistec", "Steak", "🥩", "carnes"),
  p("Cerdo", "Schweinefleisch", "🥩", "carnes"),
  p("Chuleta", "Schnitzel", "🥩", "carnes"),
  p("Pavo", "Putenbrust", "🍗", "carnes"),
  p("Tocineta", "Speck", "🥓", "carnes"),
  p("Salchichas", "Bratwurst", "🌭", "carnes"),
  p("Salchichas Wiener", "Wiener Würstchen", "🌭", "carnes"),
  p("Jamón", "Schinken", "🍖", "carnes"),
  p("Salami", "Salami", "🍖", "carnes"),
  p("Salmón", "Lachs", "🐟", "carnes"),
  p("Filete de pescado", "Fischfilet", "🐟", "carnes"),
  p("Camarones", "Garnelen", "🍤", "carnes"),

  // Lácteos y huevos
  p("Leche", "Milch", "🥛", "lacteos"),
  p("Leche de avena", "Hafermilch", "🥛", "lacteos"),
  p("Leche de almendras", "Mandelmilch", "🥛", "lacteos"),
  p("Huevos", "Eier", "🥚", "lacteos"),
  p("Mantequilla", "Butter", "🧈", "lacteos"),
  p("Queso en lonchas", "Schnittkäse", "🧀", "lacteos"),
  p("Queso rallado", "Reibekäse", "🧀", "lacteos"),
  p("Gouda", "Gouda", "🧀", "lacteos"),
  p("Mozzarella", "Mozzarella", "🧀", "lacteos"),
  p("Parmesano", "Parmesan", "🧀", "lacteos"),
  p("Feta", "Feta", "🧀", "lacteos"),
  p("Queso crema", "Frischkäse", "🧀", "lacteos"),
  p("Requesón", "Quark", "🥣", "lacteos"),
  p("Skyr", "Skyr", "🥣", "lacteos"),
  p("Yogur", "Joghurt", "🥣", "lacteos"),
  p("Yogur griego", "Griechischer Joghurt", "🥣", "lacteos"),
  p("Crema de leche", "Sahne", "🥛", "lacteos"),
  p("Crema agria", "Schmand", "🥛", "lacteos"),

  // Panadería
  p("Pan", "Brot", "🍞", "panaderia"),
  p("Pan integral", "Vollkornbrot", "🍞", "panaderia"),
  p("Pan de centeno", "Roggenbrot", "🍞", "panaderia"),
  p("Panecillos", "Brötchen", "🥐", "panaderia"),
  p("Pan de molde", "Toastbrot", "🍞", "panaderia"),
  p("Baguette", "Baguette", "🥖", "panaderia"),
  p("Croissant", "Croissant", "🥐", "panaderia"),
  p("Pretzel", "Brezel", "🥨", "panaderia"),
  p("Tortillas", "Tortillas", "🫓", "panaderia"),
  p("Pan pita", "Pitabrot", "🫓", "panaderia"),
  p("Arepas", "Arepas", "🫓", "panaderia"),
  p("Torta", "Kuchen", "🍰", "panaderia"),

  // Despensa
  p("Arroz", "Reis", "🍚", "despensa"),
  p("Pasta", "Nudeln", "🍝", "despensa"),
  p("Spätzle", "Spätzle", "🍝", "despensa"),
  p("Harina", "Mehl", "🌾", "despensa"),
  p("Azúcar", "Zucker", "🍬", "despensa"),
  p("Panela", "Rohrzucker", "🟫", "despensa"),
  p("Sal", "Salz", "🧂", "despensa"),
  p("Pimienta", "Pfeffer", "🧂", "despensa"),
  p("Aceite de oliva", "Olivenöl", "🫒", "despensa"),
  p("Aceite de girasol", "Sonnenblumenöl", "🫗", "despensa"),
  p("Vinagre", "Essig", "🫙", "despensa"),
  p("Salsa de tomate", "Passata", "🥫", "despensa"),
  p("Tomate en lata", "Dosentomaten", "🥫", "despensa"),
  p("Frijoles", "Bohnen", "🫘", "despensa"),
  p("Lentejas", "Linsen", "🫘", "despensa"),
  p("Garbanzos", "Kichererbsen", "🫘", "despensa"),
  p("Atún en lata", "Thunfisch", "🐟", "despensa"),
  p("Maíz en lata", "Mais (Dose)", "🌽", "despensa"),
  p("Leche de coco", "Kokosmilch", "🥥", "despensa"),
  p("Avena", "Haferflocken", "🥣", "despensa"),
  p("Müsli", "Müsli", "🥣", "despensa"),
  p("Miel", "Honig", "🍯", "despensa"),
  p("Mermelada", "Marmelade", "🍓", "despensa"),
  p("Mantequilla de maní", "Erdnussbutter", "🥜", "despensa"),
  p("Nutella", "Nutella", "🍫", "despensa"),
  p("Café", "Kaffee", "☕", "despensa"),
  p("Té", "Tee", "🍵", "despensa"),
  p("Caldo", "Brühe", "🥣", "despensa"),
  p("Mostaza", "Senf", "🌭", "despensa"),
  p("Mayonesa", "Mayonnaise", "🥚", "despensa"),
  p("Kétchup", "Ketchup", "🍅", "despensa"),
  p("Salsa de soya", "Sojasauce", "🍶", "despensa"),
  p("Curry", "Curry", "🍛", "despensa"),
  p("Comino", "Kreuzkümmel", "🧂", "despensa"),
  p("Paprika en polvo", "Paprikapulver", "🧂", "despensa"),
  p("Orégano", "Oregano", "🌿", "despensa"),
  p("Levadura", "Hefe", "🍞", "despensa"),
  p("Sauerkraut", "Sauerkraut", "🥬", "despensa"),
  p("Pepinillos", "Gewürzgurken", "🥒", "despensa"),
  p("Aceitunas", "Oliven", "🫒", "despensa"),

  // Congelados
  p("Pizza congelada", "Tiefkühlpizza", "🍕", "congelados"),
  p("Papas a la francesa", "Pommes", "🍟", "congelados"),
  p("Verduras congeladas", "TK-Gemüse", "🥦", "congelados"),
  p("Espinaca congelada", "TK-Spinat", "🥬", "congelados"),
  p("Frutos rojos congelados", "TK-Beeren", "🫐", "congelados"),
  p("Pescado congelado", "TK-Fisch", "🐟", "congelados"),
  p("Helado", "Eis", "🍨", "congelados"),
  p("Hielo", "Eiswürfel", "🧊", "congelados"),

  // Bebidas
  p("Agua con gas", "Sprudelwasser", "🫧", "bebidas"),
  p("Agua sin gas", "Stilles Wasser", "💧", "bebidas"),
  p("Jugo de naranja", "Orangensaft", "🧃", "bebidas"),
  p("Jugo de manzana", "Apfelsaft", "🧃", "bebidas"),
  p("Apfelschorle", "Apfelschorle", "🧃", "bebidas"),
  p("Limonada", "Limonade", "🍋", "bebidas"),
  p("Coca-Cola", "Cola", "🥤", "bebidas"),
  p("Club Mate", "Club Mate", "🧉", "bebidas"),
  p("Cerveza", "Bier", "🍺", "bebidas"),
  p("Vino tinto", "Rotwein", "🍷", "bebidas"),
  p("Vino blanco", "Weißwein", "🥂", "bebidas"),

  // Snacks
  p("Papas fritas", "Chips", "🥔", "snacks"),
  p("Galletas", "Kekse", "🍪", "snacks"),
  p("Chocolate", "Schokolade", "🍫", "snacks"),
  p("Gomitas", "Gummibärchen", "🍬", "snacks"),
  p("Nueces", "Nüsse", "🌰", "snacks"),
  p("Almendras", "Mandeln", "🥜", "snacks"),
  p("Maní", "Erdnüsse", "🥜", "snacks"),
  p("Barritas de cereal", "Müsliriegel", "🍫", "snacks"),
  p("Palomitas", "Popcorn", "🍿", "snacks"),
  p("Palitos salados", "Salzstangen", "🥨", "snacks"),

  // Limpieza
  p("Papel higiénico", "Toilettenpapier", "🧻", "limpieza"),
  p("Toallas de cocina", "Küchenrolle", "🧻", "limpieza"),
  p("Detergente de ropa", "Waschmittel", "🧺", "limpieza"),
  p("Suavizante", "Weichspüler", "🧺", "limpieza"),
  p("Lavaplatos", "Spülmittel", "🧼", "limpieza"),
  p("Pastillas lavavajillas", "Spülmaschinentabs", "🧼", "limpieza"),
  p("Bolsas de basura", "Müllbeutel", "🗑️", "limpieza"),
  p("Limpiador multiusos", "Allzweckreiniger", "🧽", "limpieza"),
  p("Limpiador de baño", "Badreiniger", "🚿", "limpieza"),
  p("Limpiavidrios", "Glasreiniger", "🪟", "limpieza"),
  p("Esponjas", "Schwämme", "🧽", "limpieza"),
  p("Trapos", "Putzlappen", "🧽", "limpieza"),
  p("Papel aluminio", "Alufolie", "🌫️", "limpieza"),
  p("Papel para hornear", "Backpapier", "📄", "limpieza"),

  // Cuidado personal
  p("Pasta de dientes", "Zahnpasta", "🪥", "cuidado"),
  p("Cepillo de dientes", "Zahnbürste", "🪥", "cuidado"),
  p("Hilo dental", "Zahnseide", "🦷", "cuidado"),
  p("Champú", "Shampoo", "🧴", "cuidado"),
  p("Acondicionador", "Spülung", "🧴", "cuidado"),
  p("Gel de ducha", "Duschgel", "🧴", "cuidado"),
  p("Jabón de manos", "Handseife", "🧼", "cuidado"),
  p("Desodorante", "Deo", "🧴", "cuidado"),
  p("Crema corporal", "Bodylotion", "🧴", "cuidado"),
  p("Protector solar", "Sonnencreme", "☀️", "cuidado"),
  p("Máquina de afeitar", "Rasierer", "🪒", "cuidado"),
  p("Espuma de afeitar", "Rasierschaum", "🪒", "cuidado"),
  p("Toallas higiénicas", "Binden", "🩹", "cuidado"),
  p("Tampones", "Tampons", "🩹", "cuidado"),
  p("Pañuelos", "Taschentücher", "🤧", "cuidado"),
  p("Curitas", "Pflaster", "🩹", "cuidado"),
  p("Ibuprofeno", "Ibuprofen", "💊", "cuidado"),

  // Mascotas
  p("Comida de perro", "Hundefutter", "🐕", "mascotas"),
  p("Comida de gato", "Katzenfutter", "🐈", "mascotas"),
  p("Snacks para perro", "Hundesnacks", "🦴", "mascotas"),
  p("Arena para gato", "Katzenstreu", "🐈", "mascotas"),
  p("Bolsas para perro", "Hundekotbeutel", "🗑️", "mascotas"),

  // Otros
  p("Pilas", "Batterien", "🔋", "otros"),
  p("Bombillo", "Glühbirne", "💡", "otros"),
  p("Velas", "Kerzen", "🕯️", "otros"),
  p("Flores", "Blumen", "💐", "otros"),
  p("Estampillas", "Briefmarken", "📮", "otros"),
  p("Bolsa de tela", "Stofftasche", "🛍️", "otros"),
];
